// Millipede distribution points in Nepal
const millipedePoints = [
    // Glomerida - Glomeridae
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "crassipes", lat: 27.20386, lon: 87.464502 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "gorkhalis", lat: 28.045647, lon: 84.631087 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "gorkhalis", lat: 27.98539, lon: 84.630633 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "khumbua", lat: 27.83277, lon: 86.746399 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "khumbua", lat: 27.901691, lon: 86.894647 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "nagarjunga", lat: 27.744675, lon: 85.268067 },
    { order: "Glomerida", family: "Glomeridae", subfamily: "Doderiinae", tribe: "NA", genus: "Hyleoglomeris", species: "tinjurana", lat: 27.199902, lon: 87.46934 },
    
    // Sphaerotheriida - Zephroniidae
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "Doderiinae", tribe: "NA", genus: "Kophosphaera", species: "excavata", lat: 27.656439, lon: 85.180041 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "Doderiinae", tribe: "NA", genus: "Kophosphaera", species: "martensi", lat: 28.313552, lon: 83.839932 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "Doderiinae", tribe: "NA", genus: "Kophosphaera", species: "politissima", lat: 27.657703, lon: 87.910006 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "NA", tribe: "NA", genus: "Kophosphaera", species: "politissima", lat: 27.611755, lon: 87.875046 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "NA", tribe: "NA", genus: "Kophosphaera", species: "shivapuri", lat: 27.80925, lon: 85.387725 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "NA", tribe: "NA", genus: "Zephronia", species: "nepalensis", lat: 27.010641, lon: 87.925383 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "NA", tribe: "NA", genus: "Zephronia", species: "nepalensis", lat: 27.090529, lon: 87.913849 },
    { order: "Sphaerotheriida", family: "Zephroniidae", subfamily: "NA", tribe: "NA", genus: "Zephronia", species: "nepalensis", lat: 27.124438, lon: 87.904898 },
    
    // Polyzoniida - Hirudisomatidae
    { order: "Polyzoniida", family: "Hirudisomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalozonium", species: "trimaculatum", lat: 28.004079, lon: 85.570456 },
    { order: "Polyzoniida", family: "Hirudisomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalozonium", species: "trimaculatum", lat: 27.99456, lon: 85.536616 },
    { order: "Polyzoniida", family: "Hirudisomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalozonium", species: "trimaculatum", lat: 28.169063, lon: 85.55246 },
    { order: "Polyzoniida", family: "Hirudisomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalozonium", species: "trimaculatum", lat: 28.160334, lon: 85.61341 },
    { order: "Polyzoniida", family: "Hirudisomatidae", subfamily: "NA", tribe: "NA", genus: "Hirudicryptus", species: "quintumelementum", lat: 27.81208, lon: 85.384353 },
    
    // Julida - Julidae
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "bilineatus", lat: 29.170822, lon: 82.935022 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "bilineatus", lat: 28.8748, lon: 82.993203 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "bilineatus", lat: 29.155909, lon: 83.031109 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "bilineatus", lat: 29.144828, lon: 82.938958 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "nepalensis", lat: 28.716484, lon: 83.666791 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "nepalensis", lat: 28.715834, lon: 83.649702 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "nepalensis", lat: 28.61522, lon: 83.026426 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "nepalensis", lat: 27.633407, lon: 87.44944 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "niger", lat: 27.620787, lon: 87.959308 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "niger", lat: 27.653657, lon: 87.935906 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "niger", lat: 28.440891, lon: 84.850679 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "niger", lat: 27.633407, lon: 87.44944 },
    { order: "Julida", family: "Julidae", subfamily: "Julinae", tribe: "NA", genus: "Anaulaciulus", species: "niger", lat: 28.37479, lon: 84.716037 },
    
    // Julida - Julidae - Nepalmatoiulus
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "deharvengi", lat: 28.606475, lon: 84.155112 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "deharvengi", lat: 28.66759, lon: 84.02467 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "deharvengi", lat: 28.531483, lon: 84.339395 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "dhaulagiri", lat: 28.61522, lon: 83.026426 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "dhaulagiri", lat: 28.500026, lon: 83.065688 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.716205, lon: 83.665493 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.696986, lon: 83.619878 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 27.179581, lon: 87.45283 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.21441, lon: 85.524783 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.527271, lon: 83.907348 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.493159, lon: 83.892909 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.469933, lon: 83.868961 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.396007, lon: 83.764363 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.391198, lon: 83.822677 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "generalis", lat: 28.634735, lon: 83.39041 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "hyalilobus", lat: 29.170822, lon: 82.935022 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "hyalilobus", lat: 28.976491, lon: 82.880479 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "hyalilobus", lat: 28.8748, lon: 82.993203 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "hyalilobus", lat: 28.500026, lon: 83.065688 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "ivanloebli", lat: 28.118731, lon: 85.56359 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "ivanloebli", lat: 28.4012, lon: 84.737539 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "ivanloebli", lat: 28.013905, lon: 85.494718 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "ivanloebli", lat: 27.998384, lon: 85.552157 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "ivanloebli", lat: 28.112586, lon: 85.336817 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "juxtapositus", lat: 28.261851, lon: 83.77579 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "juxtapositus", lat: 28.373867, lon: 83.804725 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "martensi", lat: 27.83277, lon: 86.746399 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "martensi", lat: 27.901691, lon: 86.894647 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "maurièsi", lat: 28.443002, lon: 84.848015 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "maurièsi", lat: 28.4012, lon: 84.737539 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "maurièsi", lat: 28.445505, lon: 84.840385 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "maurièsi", lat: 28.259378, lon: 84.942325 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "pineti", lat: 28.641394, lon: 83.661259 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.887337, lon: 85.866894 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.804626, lon: 85.914443 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.570331, lon: 85.406561 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.426156, lon: 85.59831 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.433106, lon: 85.593764 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "smetanai", lat: 27.744876, lon: 85.265968 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "sympatricus", lat: 28.500026, lon: 83.065688 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "uncus", lat: 27.062569, lon: 87.924207 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "uncus", lat: 27.099143, lon: 87.945488 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "uncus", lat: 27.080583, lon: 87.921427 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "uncus", lat: 27.120838, lon: 87.915148 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "uncus", lat: 27.090529, lon: 87.913849 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "zachonoides", lat: 28.624648, lon: 83.609874 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "karnaliensis", lat: 29.893611, lon: 81.918611 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "karnaliensis", lat: 29.906389, lon: 81.926667 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "karnaliensis", lat: 29.9, lon: 81.918611 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "karnaliensis", lat: 29.906389, lon: 81.919722 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "humlaensis", lat: 29.696389, lon: 82.073889 },
    { order: "Julida", family: "Julidae", subfamily: "Oncoiulinae", tribe: "Leucogeorgiini", genus: "Nepalmatoiulus", species: "humlaensis", lat: 29.696389, lon: 82.101111 },
    
    // Chordeumatida - Entomobielziidae
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "ausobskyi", lat: 28.261851, lon: 83.77579 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "ausobskyi", lat: 28.373867, lon: 83.804725 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "ausobskyi", lat: 28.493159, lon: 83.892909 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "bobanga", lat: 28.399502, lon: 83.075403 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "bobanga", lat: 28.400068, lon: 83.702553 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "daamsae", lat: 28.193935, lon: 83.890991 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "daamsae", lat: 27.652827, lon: 87.937122 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "gitanga", lat: 27.07323, lon: 87.912324 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "jaljalensis", lat: 27.507788, lon: 87.386061 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "jaljalensis", lat: 27.50522, lon: 87.286375 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "jaljalensis", lat: 27.591914, lon: 86.618057 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "jaljalensis", lat: 27.563925, lon: 87.294639 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "kathmandua", lat: 27.578551, lon: 85.383726 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "lughla", lat: 27.691809, lon: 86.733086 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "lughla", lat: 27.83277, lon: 86.746399 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "lughla", lat: 27.901691, lon: 86.894647 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "mananga", lat: 28.527253, lon: 84.305816 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "mangsingma", lat: 27.512872, lon: 87.348471 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.696986, lon: 83.619878 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.716603, lon: 83.671242 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.691233, lon: 83.610593 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.597372, lon: 83.617997 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.642994, lon: 83.598614 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "martensi", lat: 28.400863, lon: 83.702354 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "smetanai", lat: 28.034921, lon: 85.481474 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "smetanai", lat: 28.013794, lon: 85.489558 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "sp.", lat: 28.19919901, lon: 85.59887972 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "sp.", lat: 28.16602023, lon: 85.3623244 },
    { order: "Chordeumatida", family: "Entomobielziidae", subfamily: "NA", tribe: "NA", genus: "Tianella", species: "sp.", lat: 27.578005, lon: 86.441117 },
    
    // Chordeumatida - Kashmireumatidae
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "nepalensis", lat: 28.216463, lon: 85.527249 },
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "nepalensis", lat: 28.148839, lon: 85.397679 },
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "schawalleri", lat: 28.07634, lon: 84.654373 },
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "schawalleri", lat: 28.21819, lon: 84.74345 },
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "sp.", lat: 28.469933, lon: 83.868961 },
    { order: "Chordeumatida", family: "Kashmireumatidae", subfamily: "NA", tribe: "NA", genus: "Kashmireuma", species: "sp.", lat: 28.39897818, lon: 83.70251495 },
    
    // Chordeumatida - Lankasomatidae
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "deharvengi", lat: 27.578005, lon: 86.441117 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "gairiensis", lat: 27.679959, lon: 86.29263 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "gunsa", lat: 27.653657, lon: 87.935906 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "jaljalae", lat: 27.507788, lon: 87.386061 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "khumbua", lat: 27.83277, lon: 86.746399 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "khumbua", lat: 27.901691, lon: 86.894647 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "phulcokia", lat: 27.57047, lon: 85.407735 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "phulcokia", lat: 27.57047, lon: 85.407735 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "ringmoensis", lat: 27.592741, lon: 86.596206 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "taplejunga", lat: 27.543719, lon: 87.958037 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "taplejunga", lat: 27.526223, lon: 87.809277 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "taplejunga", lat: 27.603734, lon: 88.050054 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "thodunga", lat: 27.592984, lon: 86.344102 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "tragsindola", lat: 27.593316, lon: 86.618209 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 27.93470326, lon: 86.80487628 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 27.824786, lon: 86.671446 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 27.6991242, lon: 86.72604024 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 28.706836, lon: 83.655038 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 28.72455697, lon: 83.65027012 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 27.82662336, lon: 86.00755141 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 27.59028717, lon: 86.33982282 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 28.12478232, lon: 85.3829206 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 28.03344001, lon: 85.48043115 },
    { order: "Chordeumatida", family: "Lankasomatidae", subfamily: "NA", tribe: "NA", genus: "Nepalella", species: "sp.", lat: 28.01282744, lon: 85.488973 },
    
    // Platydesmida - Andrognathidae
    { order: "Platydesmida", family: "Andrognathidae", subfamily: "Bazillozoniinae", tribe: "NA", genus: "Pseudodesmus", species: "sp.", lat: null, lon: null },
    
    // Polydesmida - Haplodesmidae
    { order: "Polydesmida", family: "Haplodesmidae", subfamily: "NA", tribe: "NA", genus: "Koponenius", species: "biramus", lat: 27.599255, lon: 85.382036 },
    { order: "Polydesmida", family: "Haplodesmidae", subfamily: "NA", tribe: "NA", genus: "Koponenius", species: "schawalleri", lat: 27.572636, lon: 84.498806 },
    
    // Polydesmida - Opisotretidae
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "himalayensis", lat: 28.414459, lon: 84.407662 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "himalayensis", lat: 28.297941, lon: 84.909529 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "himalayensis", lat: 28.411662, lon: 84.893987 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "nagarjungicus", lat: 27.744036, lon: 85.267925 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "sherpa", lat: 27.982968, lon: 84.621455 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "sherpa", lat: 28.044044, lon: 84.628671 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "sherpa", lat: 28.051218, lon: 84.644731 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "sherpa", lat: 28.139634, lon: 84.689974 },
    { order: "Polydesmida", family: "Opisotretidae", subfamily: "NA", tribe: "NA", genus: "Martensodesmus", species: "sherpa", lat: 27.999527, lon: 84.930375 },
    
    // Polydesmida - Paradoxosomatidae - Anoplodesmus
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "affinis", lat: 27.571703, lon: 85.406413 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.643571, lon: 87.447343 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.638875, lon: 87.448802 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.52464, lon: 87.268873 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.497063, lon: 87.254643 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.571703, lon: 85.406413 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.805677, lon: 85.366622 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.067366, lon: 87.914487 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.00948, lon: 87.929874 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.062846, lon: 87.924963 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.10041, lon: 87.942124 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.09415, lon: 87.914116 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.080583, lon: 87.921427 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.120838, lon: 87.915148 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.153257, lon: 87.886078 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.499706, lon: 88.002968 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.509704, lon: 87.989194 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.348864, lon: 87.855622 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.493683, lon: 87.913963 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.627656, lon: 87.940988 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.656258, lon: 87.906152 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.606339, lon: 86.297079 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.339667, lon: 86.920258 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "cylindricus", lat: 27.601703, lon: 86.327807 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "magnus", lat: 27.102941, lon: 87.956722 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.112293, lon: 85.334933 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.084721, lon: 85.407768 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.071852, lon: 85.434748 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.439621, lon: 84.857906 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 27.643571, lon: 87.447343 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.36386, lon: 84.728963 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.387324, lon: 84.731975 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.376955, lon: 84.721334 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.521988, lon: 84.232101 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.545997, lon: 84.286276 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 28.532135, lon: 84.339422 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "martensi", lat: 27.595232, lon: 86.547648 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "schawalleri", lat: 27.52464, lon: 87.268873 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "schawalleri", lat: 27.497063, lon: 87.254643 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "similis", lat: 27.679716, lon: 86.252729 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "similis", lat: 27.656395, lon: 86.198247 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "similis", lat: 27.824027, lon: 86.007296 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "similis", lat: 27.824027, lon: 86.007296 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "spinosus", lat: 27.588047, lon: 86.74256 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "sp.", lat: 27.4706443, lon: 85.51389497 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "sp.", lat: 28.62064092, lon: 83.61243176 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Anoplodesmus", species: "sp.", lat: 27.17974327, lon: 87.45242469 },
    
    // Polydesmida - Paradoxosomatidae - Beronodesmoides
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "anteriporus", lat: 27.52719, lon: 87.841442 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "anteriporus", lat: 27.647434, lon: 87.444638 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "anteriporus", lat: 27.508091, lon: 88.016699 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "anteriporus", lat: 27.494047, lon: 87.983297 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "bifidus", lat: 27.747514, lon: 86.00632 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "longifemoratus", lat: 27.459217, lon: 86.892246 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "martensi", lat: 27.080583, lon: 87.921427 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "montigena", lat: 27.824786, lon: 86.671446 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmoides", species: "typicus", lat: 28.441177, lon: 84.842248 },
    
    // Polydesmida - Paradoxosomatidae - Beronodesmus
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "curtispinus", lat: 29.156182, lon: 83.033767 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "gorkhalis", lat: 28.441563, lon: 84.843045 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "gorkhalis", lat: 28.052204, lon: 84.761797 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "gorkhalis", lat: 28.223341, lon: 84.744387 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "gorkhalis", lat: 28.8748, lon: 82.993203 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 28.503313, lon: 83.066245 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.464722, lon: 87.224677 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.52464, lon: 87.268873 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.497063, lon: 87.254643 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.578298, lon: 86.783743 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.00948, lon: 87.929874 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "latispinosus", lat: 27.080583, lon: 87.921427 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "distospinosus", lat: 27.627656, lon: 87.940988 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "distospinosus", lat: 27.493683, lon: 87.913963 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "distospinosus", lat: 27.508091, lon: 88.016699 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "distospinosus", lat: 27.494047, lon: 87.983297 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.763206, lon: 87.849729 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.660015, lon: 87.940005 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 28.503313, lon: 83.066245 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.633407, lon: 87.44944 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.204165, lon: 87.466116 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 27.143634, lon: 87.405249 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 28.07634, lon: 84.654373 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "longispinus", lat: 28.21819, lon: 84.74345 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "martensi", lat: 28.608484, lon: 83.640553 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "martensi", lat: 28.632227, lon: 83.613769 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "minutus", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "pallidus", lat: 28.216195, lon: 85.526823 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "serratus", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "serratus", lat: 27.494047, lon: 87.983297 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "simplex", lat: 28.333299, lon: 83.846013 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Chamberliniini", genus: "Beronodesmus", species: "sinuatospinus", lat: 27.00948, lon: 87.929874 },
    
    // Polydesmida - Paradoxosomatidae - Chondromorpha
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Chondromorpha", species: "greke", lat: 27.960222, lon: 82.234269 },
    
    // Polydesmida - Paradoxosomatidae - Delarthrum
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "aberrans", lat: 27.614824, lon: 86.228442 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "aberrans", lat: 27.824027, lon: 86.007296 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "aberrans", lat: 27.590006, lon: 86.340332 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "aberrans", lat: 27.832357, lon: 86.091558 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "aberrans", lat: 27.601703, lon: 86.327807 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "affinis", lat: 28.28562, lon: 83.8924 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "affinis", lat: 28.31417, lon: 83.844777 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "alatum", lat: 27.520797, lon: 87.269472 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "andreevi", lat: 28.345067, lon: 83.815347 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "arunense", lat: 27.524915, lon: 87.268597 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "arunense", lat: 27.497391, lon: 87.254715 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "arunense", lat: 27.465996, lon: 87.222367 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "arunense", lat: 27.396045, lon: 87.213414 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "beroni", lat: 28.201307, lon: 83.937815 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "beroni", lat: 27.867235, lon: 83.533983 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "beroni", lat: 27.976946, lon: 85.218282 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "bifidum", lat: 27.204165, lon: 87.466116 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "bifidum", lat: 27.143634, lon: 87.405249 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "chulingensis", lat: 28.439621, lon: 84.857906 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "chulingensis", lat: 28.36386, lon: 84.728963 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "chulingensis", lat: 28.376955, lon: 84.721334 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "chulingensis", lat: 28.4012, lon: 84.737539 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "communicans", lat: 28.706836, lon: 83.655038 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "curtisoma", lat: 27.524915, lon: 87.268597 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "curtisoma", lat: 27.497391, lon: 87.254715 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "curtum", lat: 27.972544, lon: 85.215365 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "curtum", lat: 28.216995, lon: 85.514586 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "densesetosum", lat: 28.424623, lon: 83.408248 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "elegans", lat: 27.610467, lon: 85.390371 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "elegans", lat: 27.800069, lon: 85.357682 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "extremum", lat: 27.504087, lon: 87.796886 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "facile", lat: 27.504087, lon: 87.796886 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "fechteri", lat: 28.718865, lon: 83.668402 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "fechteri", lat: 28.753552, lon: 83.689226 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "foveatum", lat: 28.045936, lon: 85.205907 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "foveatum", lat: 28.108297, lon: 85.29264 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "furcatum", lat: 27.570019, lon: 85.405226 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "furcatum", lat: 28.161108, lon: 85.34046 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "furcatum", lat: 27.972544, lon: 85.215365 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "gracile", lat: 27.610467, lon: 85.390371 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "granulosum", lat: 27.497831, lon: 87.254117 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "granulosum", lat: 27.465549, lon: 87.228497 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "granulosum", lat: 27.563585, lon: 87.305007 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "granulosum", lat: 27.552841, lon: 87.282741 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "heterotergale", lat: 27.972544, lon: 85.215365 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "hirsutum", lat: 28.706836, lon: 83.655038 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "hirsutum", lat: 28.723474, lon: 83.639523 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "hirsutum", lat: 28.424623, lon: 83.408248 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "intermedium", lat: 28.256656, lon: 84.882625 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "intermedium", lat: 28.297387, lon: 84.908459 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "invocatum", lat: 27.627656, lon: 87.940988 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "invocatum", lat: 27.525848, lon: 87.808222 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "kuznetsovi", lat: 28.514437, lon: 83.064862 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "longisetum", lat: 27.733306, lon: 85.257931 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "longisetum", lat: 27.958857, lon: 85.040907 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "longispinum", lat: 27.008274, lon: 87.923901 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "modestum", lat: 27.632504, lon: 87.450153 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "nyakensis", lat: 28.443677, lon: 84.892289 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "philosophicum", lat: 28.412234, lon: 84.886706 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "philosophicum", lat: 28.34966, lon: 84.891637 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "planifemur", lat: 28.313044, lon: 83.829437 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "prolixum", lat: 28.312606, lon: 83.825791 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "quadridentatum", lat: 28.350512, lon: 83.665905 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "schawalleri", lat: 27.651966, lon: 87.907869 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "schawalleri", lat: 27.378461, lon: 87.869334 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "schawalleri", lat: 27.464939, lon: 87.228998 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "schawalleri", lat: 27.500451, lon: 87.255522 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "setosum", lat: 27.872502, lon: 83.544003 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 28.087976, lon: 85.401876 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 28.111404, lon: 85.292681 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.566309, lon: 86.84644 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.57728, lon: 86.78181 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.57287, lon: 86.54979 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.59283, lon: 86.645845 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.594579, lon: 86.769049 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "silvestre", lat: 27.432169, lon: 86.911815 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "similis", lat: 28.447407, lon: 83.692799 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "similis", lat: 28.398044, lon: 83.700001 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "simplex", lat: 28.349071, lon: 84.896816 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "simplex", lat: 28.40982, lon: 84.896923 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "simulans", lat: 27.968448, lon: 86.241446 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spectabile", lat: 28.679388, lon: 83.63204 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spinigerum", lat: 28.058319, lon: 84.81063 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spinigerum", lat: 28.137819, lon: 84.852888 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spinigerum", lat: 28.140379, lon: 84.688234 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spinigerum", lat: 27.959787, lon: 84.996673 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "spinigerum", lat: 27.980149, lon: 84.917416 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "splendens", lat: 27.497314, lon: 87.25438 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "splendens", lat: 27.525462, lon: 87.268081 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "splendens", lat: 27.505215, lon: 88.000426 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "sublatum", lat: 27.632504, lon: 87.450153 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "subsimulans", lat: 27.510683, lon: 87.859917 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "subsimulans", lat: 27.540656, lon: 87.954804 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.9, lon: 81.918611 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.90638, lon: 81.919722 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.893611, lon: 81.918611 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.906389, lon: 81.926667 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.887778, lon: 81.925278 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.893611, lon: 81.926667 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.696389, lon: 82.073889 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.752778, lon: 82.101111 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.537778, lon: 82.076111 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.545278, lon: 82.125556 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.357222, lon: 82.148611 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.395278, lon: 82.158611 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "telnovi", lat: 29.377139, lon: 82.152881 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "tenuitergale", lat: 28.112214, lon: 85.339456 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "tergalis", lat: 27.793155, lon: 86.217405 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "tuberculatum", lat: 28.251284, lon: 84.735202 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "typicum", lat: 28.005792, lon: 85.380271 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.499186, lon: 87.940087 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.419261, lon: 87.885641 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.482496, lon: 87.909564 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.499186, lon: 87.940087 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.153661, lon: 87.885799 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.035046, lon: 87.906839 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.063111, lon: 87.925348 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.067254, lon: 87.918757 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.178972, lon: 87.451339 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.139795, lon: 87.407282 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Polydrepanani", genus: "Delarthrum", species: "uncum", lat: 27.207034, lon: 87.461392 },
    
    // Polydesmida - Paradoxosomatidae - Hirtodrepanum
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.632024, lon: 83.612909 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.709029, lon: 83.661492 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.628176, lon: 83.60807 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.535224, lon: 84.337245 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.326626, lon: 83.843704 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.260964, lon: 83.776082 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.380889, lon: 83.806022 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.400826, lon: 83.700422 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 28.195516, lon: 83.892723 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Hirtodrepanum", species: "latigonopum", lat: 27.063425, lon: 87.925093 },
    
    // Polydesmida - Paradoxosomatidae - Kronopolites
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Kronopolites", species: "coriaceus", lat: 28.313701, lon: 83.828313 },
    
    // Polydesmida - Paradoxosomatidae - Orthomorpha
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Orthomorphini", genus: "Orthomorpha", species: "coarctata", lat: 27.928213, lon: 85.14333 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Orthomorphini", genus: "Orthomorpha", species: "coarctata", lat: 28.006284, lon: 84.820916 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Orthomorphini", genus: "Orthomorpha", species: "coarctata", lat: 28.001923, lon: 84.924182 },
    
    // Polydesmida - Paradoxosomatidae - Oxidus
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Oxidus", species: "gracilis", lat: 27.700655, lon: 85.308576 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Oxidus", species: "gracilis", lat: 28.215763, lon: 83.992082 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Sulciferini", genus: "Oxidus", species: "gracilis", lat: 27.92354, lon: 85.157062 },
    
    // Polydesmida - Paradoxosomatidae - Pocockina
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Pocockina", species: "schawalleri", lat: 27.577376, lon: 84.504202 },
    
    // Polydesmida - Paradoxosomatidae - Substrongylosoma
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Paradoxosomatini", genus: "Substrongylosoma", species: "bifurcatum", lat: 27.578298, lon: 86.783743 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Paradoxosomatini", genus: "Substrongylosoma", species: "exiguum", lat: 27.313174, lon: 86.937529 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Paradoxosomatini", genus: "Substrongylosoma", species: "schawalleri", lat: 27.525985, lon: 87.805593 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Paradoxosomatinae", tribe: "Paradoxosomatini", genus: "Substrongylosoma", species: "schawalleri", lat: 27.654673, lon: 87.921955 },
    
    // Polydesmida - Paradoxosomatidae - Touranella
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Touranella", species: "himalayaensis", lat: 27.154103, lon: 87.886002 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Touranella", species: "himalayaensis", lat: 27.080583, lon: 87.921427 },
    { order: "Polydesmida", family: "Paradoxosomatidae", subfamily: "Alogolykinae", tribe: "Alogolykini", genus: "Touranella", species: "pilosa", lat: 27.634851, lon: 87.449884 },
    
    // Polydesmida - Polydesmidae - Epanerchodus
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "anachoretus", lat: 27.590006, lon: 86.340332 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "buddhis", lat: 28.8748, lon: 82.993203 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "occultus", lat: 28.706836, lon: 83.655038 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "occultus", lat: 28.256255, lon: 83.775306 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "occultus", lat: 28.383315, lon: 83.809871 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "sacer", lat: 28.449848, lon: 84.831048 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "sacer", lat: 28.261862, lon: 84.941488 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "sacer", lat: 28.350854, lon: 84.728293 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "theocraticus", lat: 27.521129, lon: 87.807195 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "theocraticus", lat: 27.620787, lon: 87.959308 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "telnovi", lat: 29.933013, lon: 81.93589 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "theosophicus", lat: 28.111397, lon: 85.33801 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Epanerchodus", species: "sp.", lat: 27.758671, lon: 87.548681 },
    
    // Polydesmida - Polydesmidae - Glenniea
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Glenniea", species: "martensi", lat: 28.044361, lon: 84.628317 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Glenniea", species: "martensi", lat: 28.003008, lon: 84.629797 },
    
    // Polydesmida - Polydesmidae - Himalodesmus
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "audax", lat: 27.573643, lon: 85.40599 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "benefactor", lat: 27.532995, lon: 87.954022 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.414685, lon: 84.405902 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.41072, lon: 84.888673 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.409677, lon: 84.893488 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.137559, lon: 84.853866 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.298537, lon: 84.90922 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.256419, lon: 84.882922 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "faustus", lat: 28.061027, lon: 84.80286 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "parvus", lat: 27.154103, lon: 87.886002 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "parvus", lat: 27.120838, lon: 87.915148 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "prosperus", lat: 27.634851, lon: 87.449884 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "pulcher", lat: 27.181106, lon: 87.456025 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "pygmaeus", lat: 28.8748, lon: 82.993203 },
    { order: "Polydesmida", family: "Polydesmidae", subfamily: "NA", tribe: "NA", genus: "Himalodesmus", species: "vigens", lat: 27.008392, lon: 87.929636 },
    
    // Polydesmida - Trichopolydesmidae - Hingstonia
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "beatae", lat: 27.620787, lon: 87.959308 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "beatae", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "beatae", lat: 27.652624, lon: 87.804197 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "beatae", lat: 27.676591, lon: 87.799738 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "eremita", lat: 27.968783, lon: 86.238501 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "falcata", lat: 28.706836, lon: 83.655038 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "fittkaui", lat: 27.758922, lon: 87.547397 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "pahakholana", lat: 27.634851, lon: 87.449884 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "perarmata", lat: 28.71512, lon: 83.672771 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "serrata", lat: 28.261862, lon: 84.941488 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "serrata", lat: 28.444205, lon: 84.850337 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "sympatrica", lat: 27.758922, lon: 87.547397 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.620787, lon: 87.959308 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.543719, lon: 87.958037 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.609725, lon: 88.048952 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.626731, lon: 87.95659 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.534943, lon: 87.990923 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.521129, lon: 87.807195 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "variata", lat: 27.572751, lon: 87.976023 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Hingstonia", species: "sp.", lat: 27.56815366, lon: 87.97492699 },
    
    // Polydesmida - Trichopolydesmidae - Sholaphilus
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "asceticus", lat: 28.424254, lon: 83.851329 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "asceticus", lat: 28.292564, lon: 83.824561 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "asceticus", lat: 28.288146, lon: 83.884865 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "asceticus", lat: 28.315009, lon: 83.843934 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "dalai", lat: 28.256255, lon: 83.775306 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "gompa", lat: 27.478654, lon: 87.964047 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "lama", lat: 28.042189, lon: 85.20739 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "lama", lat: 28.108348, lon: 85.297885 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "martensi", lat: 28.414941, lon: 84.40747 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "martensi", lat: 28.385845, lon: 84.400387 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "martensi", lat: 28.467317, lon: 84.379798 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "martensi", lat: 28.493187, lon: 84.50513 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "martensi", lat: 28.534431, lon: 84.341358 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "monachus", lat: 27.52425, lon: 87.268861 },
    { order: "Polydesmida", family: "Trichopolydesmidae", subfamily: "NA", tribe: "NA", genus: "Sholaphilus", species: "monachus", lat: 27.497211, lon: 87.253927 },
    
    // Spirostreptida - Cambalopsidae
    { order: "Spirostreptida", family: "Cambalopsidae", subfamily: "Glyphiulinae", tribe: "NA", genus: "Podoglyphiulus", species: "elegans", lat: 27.594801, lon: 85.401456 },
    { order: "Spirostreptida", family: "Cambalopsidae", subfamily: "Cambalopsinae", tribe: "NA", genus: "Trachyjulus", species: "wilsonae", lat: 28.27254, lon: 83.979256 },
    { order: "Spirostreptida", family: "Cambalopsidae", subfamily: "Cambalopsinae", tribe: "NA", genus: "Trachyjulus", species: "wilsonae", lat: 27.594801, lon: 85.401456 },
    
    // Spirostreptida - Harpagophoridae
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "broelemanni", lat: 28.36222, lon: 84.105065 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "broelemanni", lat: 28.194578, lon: 83.891973 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "broelemanni", lat: 28.369848, lon: 84.127161 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "hyatti", lat: 28.315009, lon: 83.843934 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "hyatti", lat: 28.144559, lon: 83.93724 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "malayus", lat: 27.697504, lon: 84.427875 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "malayus", lat: 27.56522, lon: 84.097853 },
    { order: "Spirostreptida", family: "Harpagophoridae", subfamily: "Harpagophorinae", tribe: "Gonoplectini", genus: "Gonoplectus", species: "lindbergi", lat: 26.644483, lon: 88.027548 },
    
    // Spirobolida - Pachybolidae
    { order: "Spirobolida", family: "Pachybolidae", subfamily: "Trigoniulinae", tribe: "NA", genus: "Trigoniulus", species: "corralinus", lat: 27.730944, lon: 85.320841 }
];

// Export for use in other files if needed (for module systems)
if (typeof module !== 'undefined' && module.exports) {
    module.exports = millipedePoints;
}
